version: 2

sources:
  - name: raw_data
    database: warehouse     # ajuste se seu DB for outro
    schema: public          # ajuste se os dados estiverem em outro schema
    tables:
      - name: olist_products_dataset
      - name: product_category_name_translation
      - name: olist_sellers_dataset
      - name: olist_order_items_dataset
      - name: olist_orders_dataset
      - name: olist_order_payments_dataset
      - name: olist_order_reviews_dataset
      - name: olist_geolocation_dataset
      - name: olist_customers_dataset